print("Step 0: Preload Labels.")

print("Loading Feature Labels...")
filePath <- paste(dataSetLocation,"/features.txt",sep="") 
features <- read.table(filePath)
features <- features$V2 
print("Done.")

print("Loading Activity Labels...")
filePath <- paste(dataSetLocation,"/activity_labels.txt",sep="")
activities <- read.table(filePath,col.names=c("Key","Value"))
print("Done.")

print("Step 0: Done.")

print("Step 1: Loading and Merging Data Sets.")

print("Loading Subject Training file...")
filePath <- paste(dataSetLocation,"/train/subject_train.txt",sep="") 
sfile <- read.table(filePath,col.names=c("Subject"))
print("Loading Subject Testing file...")
filePath <- paste(dataSetLocation,"/test/subject_test.txt",sep="")
sfile2 <- read.table(filePath,col.names=c("Subject"))
print("Merging Subject files...")
sfile <- rbind(sfile,sfile2)
rm(sfile2)
print("Done.")

print("Loading X Training file...")
filePath <- paste(dataSetLocation,"/train/X_train.txt",sep="") 
xfile <- read.table(filePath,col.names=features)
print("Loading X Testing file...")
filePath <- paste(dataSetLocation,"/test/X_test.txt",sep="")
xfile2 <- read.table(filePath,col.names=features)
print("Merging X files...")
xfile <- rbind(xfile,xfile2)
rm(xfile2)
print("Done.")

print("Loading Y Training file...") 
filePath <- paste(dataSetLocation,"/train/y_train.txt",sep="") 
yfile <- read.table(filePath,col.names=c("Activity"))
print("Loading Y Testing file...")
filePath <- paste(dataSetLocation,"/test/y_test.txt",sep="") 
yfile2 <- read.table(filePath,col.names=c("Activity"))
print("Merging Y files...")
yfile <- rbind(yfile,yfile2)
rm(yfile2)
print("Done.")
rm(filePath)
print("Step 1: Done.")

print("Step 2: Extracting Only Means and STD Measurements.")
print("Filtering Down Gathered Data to Only Means and STDs...")
xfile <- xfile[,grep("mean|Mean|std",features)]
rm(features)
print("Done.")
print("Step 2: Done.")

print("Step 3: Use Descriptive Activity Names.")
print("Setting Activity Information to Human Readable Values...")
yfile$Activity <- activities$Value[match(yfile$Activity,activities$Key)]
rm(activities)
print("Done.")
print("Step 3: Done.")

print("Step 4: Use Descriptive Data Names.")
print("Data was loaded with Feature Labels.")
print("Step 4: Done.")

print("Step 5: Create Tidy Data Set with Average of Each Variable for Each Activity for Each Subject.")
untidyData <- cbind(sfile,yfile)
untidyData <- cbind(untidyData,xfile)
rm(sfile)
rm(yfile)
rm(xfile)
tidyData <- aggregate(x=untidyData[3:ncol(untidyData)],by=list(Subject=untidyData$Subject,Activity=untidyData$Activity),FUN="mean")
rm(untidyData)
print("Step 5: Done.")

print("Writing Finished Product to: tidy_data.txt.")
write.table(tidyData,file="tidy_data.txt",row.name=FALSE)
rm(tidyData)
print("Complete!")
